# Travis CI, Continous Integration testing http://travis-ci.org/
# Coverity scan, static code analysis https://scan.coverity.com/travis_ci

# set c as language, c# not supported
language: c

install:
  - sudo apt-get update -yqq
  - sudo apt-get install mono-devel mono-xbuild libgtk2.0-cil-dev intltool -yqq

script:
  - ./autogen.sh && make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "AJmaaeNAtrvXf2GJ2mhw8L/bieYvEKMOlSXImL7gHaaj2EMVpjivP1au5HW0t5EzMddQ4h73ksaD1qIsQt2sNI5KEoRlHF97HPlvDOjC61cSbucsYJ0OZ8hB8K3W4PnmDg5MuyX7q3t3VyHfIveim46UsF0Om9GxzU9qHSZ/GcI="

addons:
  coverity_scan:

    # GitHub project metadata
    project:
      name: horkana/Pinta
      version: 1.6
      description: Paint raster graphics with Pinta

    # Where email notification of build analysis results will be sent
    notification_email: alanhorkan+scan_notifications@gmail.com

#    build_command_prepend: ./autogen.sh

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
#    build_command: make
    build_command: "xbuild Pinta.Install.proj"

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan
#    branch_pattern: release*
